### ISSUE TITLE
Add default compiler options to all languages

### ISSUE THREAD

**Issue by snomos** [giellalt/template-lang-und#2]
It would be useful to have a section in `configure.ac` to set language specific compiler and optimisation options. Relevant options are:

- foma=yes/no (by default, that is)
- hfst=yes/no
- xfst=yes/no
- hyperminimisation=yes/no
- reversed-intersect=yes/no
- possibly also hfst-backend-format, although we'll probably just make it foma everywhere, for fastest compilation

The idea is to define a section with suitable variables in `configure.ac` and then reference these variables in the relevant places in the `m4/*.m4` files. This way we can tune the default compilation options for each language, while at the same time keep the general configuration files language independent.

This was first discussed in giellalt/lang-crk#3.

**Comment by snomos** [comment]
The initial default values should reflect the defaults we want, which are:

- foma=no
- hfst=yes
- xfst=no
- hyperminimisation=no
- reversed-intersect=no

Another compilation option is alignment, but that one is already set to yes for all languages, and should probably just stay like that. If needed, we can add an option for that one later on.

And as mentioned above, we should just make the hfst-backend=foma as a default everywhere.

**Comment by flammie** [comment]
I have added a place for some default options finally. sorry for the delay I had to tread carefully for the first template merge.

For the larger theme of making the infra more like any modern software engineering project / framework, it is my long term goal as well.

**Comment by aarppe** [comment]
As for XFST, in the case of crk, the XFST implementation of TWOLC did not work properly with the morphophonology, so we have had to `hfst-twolc`. In the case of srs, the XFST compiler breaks with `twosided flag-diacritics`, so there as well we have had to use `hfst-xfst`. Maybe XFST works as it should for other languages, and it certainly is faster than HFST, but since XFST is known to not to work, I'm not convinced we really should be promoting its use at all anymore.

**Comment by snomos** [comment]
> As for XFST, in the case of crk, the XFST implementation of TWOLC, the `twolc` compiler, did not work properly with the morphophonology, so we have had to `hfst-twolc`. In the case of srs, the XFST compiler `xfst` breaks with `twosided flag-diacritics`, so there as well we have had to use `hfst-xfst`. Maybe XFST works as it should for other languages, and it certainly is faster than HFST, but since XFST is known to not to work, I'm not convinced we really should be promoting its use at all anymore.

I suggest we move such general discussions to Zulip. I will reply there.

**Comment by snomos** [comment]
Discussion continued at https://giella.zulipchat.com/#narrow/stream/124585-langs-infra/topic/Default.20compiler.20options
