### ISSUE TITLE
gtgramtool 0.10.0 not >= 0.7.0?

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/template-lang-und#27]
https://github.com/divvun/GiellaLTGramTools/commit/3d83f7137ddb9abdaf38ab9285263c0b21ceb0ef bumped version to 0.10.0. Somehow, this yields
```
checking the version of gtgramtool... 0.10.0
checking whether the gtgramtool version is at least 0.7.0...
configure: error: gtgramtool needs to be updated.
```
even though https://github.com/giellalt/template-lang-und/blob/ab0921ee1e75a04739e82be4750888e8da80f1db/m4/giella-macros.m4#L688 ought to work.

Worked fine with version 0.9.0.

**Comment by albbas** [comment]
Temporary fix in https://github.com/divvun/GiellaLTGramTools/commit/8c3a59c8d381d01b19e23c64aaaf20e594e1ce97, bumped version to 1.0.0

**Comment by flammie** [comment]
is this a mac os x problem? I test with:
```automake
AC_MSG_CHECKING([is 0.10.0 ge 0.7.0])
AX_COMPARE_VERSION([0.10.0], [ge], [0.7.0], AC_MSG_RESULT([yes]), AC_MSG_RESULT([no]))
```
and get yes as expected.

**Comment by albbas** [comment]
Seems so, yes:
```
checking is 0.10.0 ge 0.7.0... no
```

**Comment by albbas** [comment]
```
❯ which autoconf 
/opt/homebrew/bin/autoconf
```

installed by homebrew

```
lang-zxx on  main [!⇡] 
❯ autoconf --version
autoconf (GNU Autoconf) 2.72
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>, <https://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```

**Comment by flammie** [comment]
https://github.com/giellalt/template-lang-und/blob/ab0921ee1e75a04739e82be4750888e8da80f1db/m4/ax_compare_version.m4 is the whole code from autoconf archive, probably changing awk to gawk or sed to g(nu)sed will fix mac's problems?

**Comment by albbas** [comment]
Or, tested it on my Ubuntu 22.04 derivative
```
checking is 0.10.0 ge 0.7.0... no
```

**Comment by snomos** [comment]
Strange, I added that AX file, and it has worked fine for me earlier exactly for solving this problem. I haven't tested the present code, though, will do soon.

**Comment by snomos** [comment]
So this seems to be something else than macOS vs *nix. But I have no idea what it could be.

**Comment by flammie** [comment]
I don't think there's another way to debug than to do step by step, it should be possible to put `set -x` in the generated `./configure` file to see what it does.

**Comment by flammie** [comment]
Here's mine:
```
+ printf '%s\n' 'configure:11678: checking is 0.10.0 ge 0.7.0'
+ printf %s 'checking is 0.10.0 ge 0.7.0... '
checking is 0.10.0 ge 0.7.0... + ax_compare_version=false
++ echo 0.10.0
++ sed -e 's/\([0-9]*\)/Z\1Z/g' -e 's/Z\([0-9]\)Z/Z0\1Z/g' -e 's/Z\([0-9][0-9]\)Z/Z0\1Z/g' -e 's/Z\([0-9][0-9][0-9]\)Z/Z0\1Z/g' -e 's/[^0-9]//g'
+ ax_compare_version_A=000000100000
++ echo 0.7.0
++ sed -e 's/\([0-9]*\)/Z\1Z/g' -e 's/Z\([0-9]\)Z/Z0\1Z/g' -e 's/Z\([0-9][0-9]\)Z/Z0\1Z/g' -e 's/Z\([0-9][0-9][0-9]\)Z/Z0\1Z/g' -e 's/[^0-9]//g'
+ ax_compare_version_B=000000070000
++ echo 'x000000100000
x000000070000'
++ sed 's/^ *//'
++ sort -r
++ sed 's/x000000100000/true/;s/x000000070000/false/;1q'
+ ax_compare_version=true
+ test true = true
+ printf '%s\n' 'configure:11712: result: yes'
+ printf '%s\n' yes
yes
+ set +x
```
it's either sed or sort unless the whole generated code is different

**Comment by snomos** [comment]
And here is mine on macOS:

```sh
+ printf '%s\n' 'configure:9446: checking is 0.10.0 ge 0.7.0'
+ printf %s 'checking is 0.10.0 ge 0.7.0... '
checking is 0.10.0 ge 0.7.0... + ax_compare_version=false
++ echo 0.10.0
++ sed -e 's/\([0-9]*\)/Z\1Z/g' -e 's/Z\([0-9]\)Z/Z0\1Z/g' -e 's/Z\([0-9][0-9]\)Z/Z0\1Z/g' -e 's/Z\([0-9][0-9][0-9]\)Z/Z0\1Z/g' -e 's/[^0-9]//g'
+ ax_compare_version_A=000000100000
++ echo 0.7.0
++ sed -e 's/\([0-9]*\)/Z\1Z/g' -e 's/Z\([0-9]\)Z/Z0\1Z/g' -e 's/Z\([0-9][0-9]\)Z/Z0\1Z/g' -e 's/Z\([0-9][0-9][0-9]\)Z/Z0\1Z/g' -e 's/[^0-9]//g'
+ ax_compare_version_B=000000070000
++ echo 'x000000100000
x000000070000'
++ sed 's/^ *//'
++ sort -r
++ sed 's/x000000100000/true/;s/x000000070000/false/;1q'
+ ax_compare_version=true
+ test true = true
+ printf '%s\n' 'configure:9480: result: yes'
+ printf '%s\n' yes
yes
```

**Comment by albbas** [comment]
This is from my linux box:
```
+ printf '%s\n' 'configure:9392: checking is 0.10.0 ge 0.7.0'
+ printf %s 'checking is 0.10.0 ge 0.7.0... '
checking is 0.10.0 ge 0.7.0... + ax_compare_version=false
++ echo 0.10.0
++ sed -e 's/\(0-9*\)/Z\1Z/g' -e 's/Z\(0-9\)Z/Z0\1Z/g' -e 's/Z\(0-90-9\)Z/Z0\1Z/g' -e 's/Z\(0-90-90-9\)Z/Z0\1Z/g' -e 's/^0-9//g'
+ ax_compare_version_A=0.10.0
++ echo 0.7.0
++ sed -e 's/\(0-9*\)/Z\1Z/g' -e 's/Z\(0-9\)Z/Z0\1Z/g' -e 's/Z\(0-90-9\)Z/Z0\1Z/g' -e 's/Z\(0-90-90-9\)Z/Z0\1Z/g' -e 's/^0-9//g'
+ ax_compare_version_B=0.7.0
++ echo 'x0.10.0
x0.7.0'
++ sed 's/^ *//'
++ sort -r
++ sed 's/x0.10.0/true/;s/x0.7.0/false/;1q'
+ ax_compare_version=false
+ test false = true
+ printf '%s\n' 'configure:9428: result: no'
+ printf '%s\n' no
no
```

**Comment by albbas** [comment]
And my mac
```
+ printf '%s\n' 'configure:9670: checking is 0.10.0 ge 0.7.0'
+ printf %s 'checking is 0.10.0 ge 0.7.0... '
checking is 0.10.0 ge 0.7.0... + ax_compare_version=false
++ echo 0.10.0
++ sed -e 's/\(0-9*\)/Z\1Z/g' -e 's/Z\(0-9\)Z/Z0\1Z/g' -e 's/Z\(0-90-9\)Z/Z0\1Z/g' -e 's/Z\(0-90-90-9\)Z/Z0\1Z/g' -e 's/^0-9//g'
+ ax_compare_version_A=0.10.0
++ echo 0.7.0
++ sed -e 's/\(0-9*\)/Z\1Z/g' -e 's/Z\(0-9\)Z/Z0\1Z/g' -e 's/Z\(0-90-9\)Z/Z0\1Z/g' -e 's/Z\(0-90-90-9\)Z/Z0\1Z/g' -e 's/^0-9//g'
+ ax_compare_version_B=0.7.0
++ echo 'x0.10.0
x0.7.0'
++ sed 's/^ *//'
++ sort -r
++ sed 's/x0.10.0/true/;s/x0.7.0/false/;1q'
+ ax_compare_version=false
+ test false = true
+ printf '%s\n' 'configure:9706: result: no'
+ printf '%s\n' no
no
```

**Comment by albbas** [comment]
So, my examples give `+ ax_compare_version_A=0.10.0`, whereas yours are: `+ ax_compare_version_A=000000100000`

**Comment by snomos** [comment]
This seems to be `sed` related then. What version of sed is used by your system, @albbas ?

Mine seems to be the system `sed` provided by macOS 14.6:

```sh
whence sed
/usr/bin/sed
```

**Comment by snomos** [comment]
What is strange is that this bug pops up now. IIRC AX_COMPARE_VERSION was introduced when Vislcg3 turned x.10.x. and the earlier version check broke. It has been working fine, and is presently used in X different cases:

- checking that giella-core is new enough
- checking that we have a new enough version of GNU Make (or compatible)
- checking the version of VislCG3
- checking the version of Saxon
- and recently also the version of gtgramtool

Except for the last one, there has been no issues. That could of course be just because the version numbers haven't been such that it has caused issues, but it still seems odd that only the gtgramtool check fails.

**Comment by flammie** [comment]
maybe fixed in newest template, it seems like an m4 quotation issue with [] in sed expressions and some very specific exceptions that may be explained in https://buildsystem-manual.sourceforge.net/M4-Quotation.html
