### ISSUE TITLE
test/src/morphology/tag_test.sh has path troubles (Bugzilla Bug 2673)

### ISSUE THREAD

**Issue by albbas** [giellalt/template-lang-und#28]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2673
Date: 2020-09-02T12:21:18+02:00
From: Trond Trosterud &lt;<trond.trosterud>&gt;
To:   Sjur Nørstebø Moshagen &lt;<sjur.n.moshagen>&gt;

Last updated: 2020-09-02T12:21:18+02:00

**Comment by flammie** [comment]
as it is now, the path to `../lexicon.lexc` is fixed after test reorg since the tests test files near the test directory now, but I don't think the extragt-tags script from core is working at least on my linux

**Comment by flammie** [comment]
I had to fix the whole script while working on it :-D
