### ISSUE TITLE
Rydda i src/ (morphology/) (Bugzilla Bug 2660)

### ISSUE THREAD

**Issue by albbas** [giellalt/template-lang-und#30]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2660
Date: 2020-04-20T16:17:00+02:00
From: Sjur Nørstebø Moshagen &lt;<sjur.n.moshagen>&gt;
To:   Sjur Nørstebø Moshagen &lt;<sjur.n.moshagen>&gt;
CC:   borre.gaup, chiara.argese

Blocker for:  #2613
Last updated: 2020-04-22T22:18:31+02:00

**Comment by flammie** [comment]
- [ ] #8 ?

**Comment by snomos** [comment]
Jepp, og alt som er nemnt her er gjort, så eg avsluttar denne saka.
